2020-08-16 11:26:32,282 - [test_register_case.py-->line:29] - ERROR: 注册失败-手机号为字符串执行失败
2020-08-16 11:26:32,283 - [test_register_case.py-->line:30] - ERROR: '无效的手机格式' != '账号已存在'
- 无效的手机格式
+ 账号已存在
Traceback (most recent call last):
  File "/Users/mlamp/Desktop/python/python-project/project_day20/test_case/test_register_case.py", line 26, in test_register
    self.assertEqual(expected['msg'],result['msg'])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: '无效的手机格式' != '账号已存在'
- 无效的手机格式
+ 账号已存在

